import React, { ReactElement } from 'react'
import Head from 'next/head'
import Header from 'components/Header'
import Footer from 'components/Footer'

interface IProps {
  children: ReactElement
}

const Layout = ({ children }: IProps) => {
  return (
    <div className='bg-primary text-cyan-50'>
      <div className='lg:max-w-[85vw] 2xl:max-w-[70vw] md:max-w-[96vw] max-w-[95vw] m-auto'>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className='min-h-[100vh] py-6'>
          { children }
        </main>
        <Footer />
      </div>
    </div>
  )
}

export default Layout
